// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgSKDhKHT4TzD8t4eLJt1iiitBFUSm6U',
    appId: '1:355480003866:web:deee4bfb0b8f2bbceff8a3',
    messagingSenderId: '355480003866',
    projectId: 'reddit-8ba38',
    authDomain: 'reddit-8ba38.firebaseapp.com',
    storageBucket: 'reddit-8ba38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzy5sgvBD-qEb8IR1y9f_n6xDWfdQ6NgE',
    appId: '1:355480003866:android:91d68a9566b44b23eff8a3',
    messagingSenderId: '355480003866',
    projectId: 'reddit-8ba38',
    storageBucket: 'reddit-8ba38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwT9umr0EGAeBloKapHo68zc8sXDGCUBM',
    appId: '1:355480003866:ios:d25d2cd5991c11d6eff8a3',
    messagingSenderId: '355480003866',
    projectId: 'reddit-8ba38',
    storageBucket: 'reddit-8ba38.firebasestorage.app',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDgSKDhKHT4TzD8t4eLJt1iiitBFUSm6U',
    appId: '1:355480003866:web:92c95ee33975f526eff8a3',
    messagingSenderId: '355480003866',
    projectId: 'reddit-8ba38',
    authDomain: 'reddit-8ba38.firebaseapp.com',
    storageBucket: 'reddit-8ba38.firebasestorage.app',
  );

}